var listTruongLop = 
[	
    new BaiHat({rootFolder: rootFolder, folder: "truongLop", 
        tenHienThi: "Bụi phấn", tenFile: "1 Quoc Ca", 
        tacGia: "Văn Cao", trinhBay: "tốp ca", 
        volume: 80, trangThai: -1, 
        autoNext: 1,  delayBeforePlay: 5, imageName: "quocKy.png"}), 
    new BaiHat({rootFolder: rootFolder, folder: "truongLop", 
        tenHienThi: "Mái trường mến yêu", tenFile: "8 Quoc Te Ca - Various Artists", 
        tacGia: "Nhạc: P. Degeyter, Lời: Eugène Pottier", trinhBay: "tốp ca",
        volume: 80, trangThai: -1, 
        autoNext: 0,  delayBeforePlay: 0, imageName: "coDang.png"}),
    new BaiHat({rootFolder: rootFolder, folder: "truongLop", 
        tenHienThi: "Hoa điểm 10", tenFile: "8 Quoc Te Ca - Various Artists", 
        tacGia: "Nhạc: P. Degeyter, Lời: Eugène Pottier", trinhBay: "tốp ca",
        volume: 80, trangThai: -1, 
        autoNext: 0,  delayBeforePlay: 0, imageName: "coDang.png"}),
    new BaiHat({rootFolder: rootFolder, folder: "truongLop", 
        tenHienThi: "Nhớ Ơn Thầy Cô", tenFile: "8 Quoc Te Ca - Various Artists", 
        tacGia: "Nhạc: P. Degeyter, Lời: Eugène Pottier", trinhBay: "tốp ca",
        volume: 80, trangThai: -1, 
        autoNext: 0,  delayBeforePlay: 0, imageName: "coDang.png"}),
    new BaiHat({rootFolder: rootFolder, folder: "truongLop", 
        tenHienThi: "Mong Ước Kỷ Niệm Xưa", tenFile: "8 Quoc Te Ca - Various Artists", 
        tacGia: "Nhạc: P. Degeyter, Lời: Eugène Pottier", trinhBay: "tốp ca",
        volume: 80, trangThai: -1, 
        autoNext: 0,  delayBeforePlay: 0, imageName: "coDang.png"}),
    new BaiHat({rootFolder: rootFolder, folder: "truongLop", 
        tenHienThi: "Khi tóc thầy bạc", tenFile: "8 Quoc Te Ca - Various Artists", 
        tacGia: "Nhạc: P. Degeyter, Lời: Eugène Pottier", trinhBay: "tốp ca",
        volume: 80, trangThai: -1, 
        autoNext: 0,  delayBeforePlay: 0, imageName: "coDang.png"}),
    new BaiHat({rootFolder: rootFolder, folder: "truongLop", 
        tenHienThi: "Người thầy", tenFile: "8 Quoc Te Ca - Various Artists", 
        tacGia: "Nhạc: P. Degeyter, Lời: Eugène Pottier", trinhBay: "tốp ca",
        volume: 80, trangThai: -1, 
        autoNext: 0,  delayBeforePlay: 0, imageName: "coDang.png"})
];